#!/bin/bash
export mistletoeVersion="0.3"
echo -e "Winter Mistletoe ${mistletoeVersion}: Configuration updater\n"
function downloadFile {
	printf "Downloading ${1}... "
	curl -fLso "${1}" "${2}" && echo "done."
	if [ "$?" != "0" ]; then
		echo "fail."
	else
		printf "Checking ${1}... "
		if [ "$(grep -i ' error' ${1})" != "" ]; then
			echo "fail."
			rm "${1}"
		else
			echo "OK."
		fi
	fi
}

mkdir -p conf
mkdir -p data
export auth=$(cat conf/auth.list)
if [ -f "conf/pointer.txt" ]; then
	# ACE potential here, but literally the only way to include `&` for now
	ptrUrl=$(echo "echo $(cat conf/pointer.txt)" | bash)
	downloadFile "list.txt" "${ptrUrl}"
else
	echo "Pointer file not found."
fi
if [ -f "data/list.tsv" ]; then
	cat data/list.tsv | while IFS= read -r line; do
		fileName="./data/$(echo "${line}" | cut -d'	' -f1)"
		# Same ACE
		fileUrlExec="echo $(echo "${line}" | cut -d'	' -f2)"
		fileUrl="$(echo "${fileUrlExec}" | bash)"
		downloadFile $fileName $fileUrl
	done
else
	echo "List file not found."
fi
exit